// export const steps = [
//   {
//     idx: 1,
//     question: "What's your gender?",
//     options: ["Female", "Male", "Non-Binary", "Prefer not to say"],
//     fieldName: "gender",
//     type: "string",
//     components: "select",
//   },
//   {
//     idx: 2,
//     question: "What shaould we call you?",
//     fieldName: "name",
//     placeholder: "First Name",
//     type: "string",
//     components: "textbox",
//   },
//   {
//     idx: 3,
//     question: "What's your goal",
//     options: ["Gain muscle", "Lose weight", "Fitness"],
//     fieldName: "goal",
//     type: "string",
//     components: "select",
//   },
//   {
//     idx: 4,
//     question: "What's your body type?",
//     options: ["Skinny", "Ideal", "Flabby", "Heavier"],
//     fieldName: "bodyType",
//     type: "string",
//     components: "select",
//   },
//   {
//     idx: 5,
//     question: "Which parts should we focus on?",
//     options: ["Arms", "Chest", "Belly", "Legs"],
//     fieldName: "focusPoint",
//     type: "string[]",
//     components: "select",
//   },
//   {
//     idx: 6,
//     question: "Any previous workout experience?",
//     options: [
//       "Yes, I workout regularly",
//       "Yes, less than a year ago",
//       "Yes, more than 1 year ago",
//       "No, I don't have any",
//     ],
//     fieldName: "priorExperience",
//     type: "string",
//     components: "select",
//   },
//   {
//     idx: 7,
//     question: "How fit are you?",
//     options: ["I'm very fit", "I'm fit", "I'm not very fit"],
//     fieldName: "fitness",
//     type: "string",
//     components: "select",
//   },
//   {
//     idx: 8,
//     question: "Do you relate to the following statement?",
//     statement: "I wish I feel more confidence in myself",
//     fieldName: "isConfidenceHigh",
//     type: "boolean",
//     components: "select",
//   },
//   {
//     idx: 9,
//     question: "How old are you?",
//     fieldName: "age",
//     placeholder: 0,
//     type: "number",
//     components: "textbox",
//   },
//   {
//     idx: 10,
//     question: "How tall are you?",
//     fieldName: "height",
//     placeholder: 0,
//     type: "number",
//     units: ["cm", "ft"],
//     components: "textbox",
//   },
//   {
//     idx: 11,
//     question: "What is your weight?",
//     fieldName: "weight",
//     placeholder: 0,
//     type: "number",
//     units: ["kg", "lbs"],
//     components: "textbox",
//   },
//   {
//     idx: 12,
//     question: "Alright, Now what is your target weight?",
//     fieldName: "targetWeight",
//     placeholder: 0,
//     type: "number",
//     units: ["kg", "lbs"],
//     components: "textbox",
//   },
//   {
//     idx: 13,
//     question: "Do you suffer from knee pain?",
//     fieldName: "haveKneePain",
//     type: "boolean",
//     components: "select",
//   },
//   {
//     idx: 14,
//     question: "How serious are your problem?",
//     options: ["Mild pain", "Quite serious"],
//     fieldName: "kneePainLevel",
//     type: "string",
//     components: "select",
//   },
//   {
//     idx: 15,
//     question: "Do you relate to the following statement?",
//     statement:
//       "I am afraid excercise and diet will take too much of my meal time",
//     fieldName: "isTimeShort",
//     type: "boolean",
//     components: "select",
//   },
//   {
//     idx: 16,
//     question: "How many pushups can you do?",
//     options: ["30+", "10-29", "6-14", "Less than 5"],
//     fieldName: "pushupCount",
//     type: "string",
//     components: "select",
//   },
//   {
//     idx: 17,
//     question: "How many do you walk daily?",
//     options: ["more than 2 hours", "1-2 hours", "Less than 1 hour"],
//     fieldName: "dailyWalkDistance",
//     type: "string",
//     components: "select",
//   },
//   {
//     idx: 18,
//     question: "Any bad habits?",
//     options: [
//       "I have a sweet tooth",
//       "I love sugary drinks",
//       "I don't sleep enough",
//       "I enjoy fast food",
//       "I eat late at night",
//     ],
//     fieldName: "badHabits",
//     type: "string[]",
//     components: "select",
//   },
//   {
//     idx: 19,
//     question: "When was the last time you were at you ideal weight?",
//     options: [
//       "Less than a year ago",
//       "1-2 years ago",
//       "More than 2 years",
//       "Never",
//     ],
//     fieldName: "lastTimeInIdealWeight",
//     type: "string",
//     components: "select",
//   },
//   {
//     idx: 20,
//     question: "How much do you sleep every night?",
//     options: [
//       "More than 8 hours",
//       "7-8 hours",
//       "6-7 hours",
//       "Less than 6 hours",
//     ],
//     fieldName: "dailySleepTime",
//     type: "string",
//     components: "select",
//   },
//   {
//     idx: 21,
//     question: "How often do you feel stressed?",
//     options: ["Not at all", "A few times a week", "Multiple times a day"],
//     fieldName: "stressedFor",
//     type: "string",
//     components: "select",
//   },
//   {
//     idx: 22,
//     question: "What is your preferred mode of exercise?",
//     options: [
//       "Walking or Hiking",
//       "Running or Jogging",
//       "Cycling",
//       "Strength Training",
//       "Yoga or Stretching",
//       "Group Fitness Classes",
//       "Swimming",
//       "Sports",
//       "Home Workouts",
//       "Not sure",
//     ],
//     fieldName: "preference",
//     type: "string[]",
//     components: "select",
//   },
//   {
//     idx: 23,
//     question: "What motivates you the most?",
//     options: [
//       "Feeling confident",
//       "Being active",
//       "Boosting immunity",
//       "Improving sleep",
//       "Feeling happier",
//       "Boosting energy",
//     ],
//     fieldName: "motivation",
//     type: "string[]",
//     components: "select",
//   },
//   {
//     idx: 24,
//     question: "Where will you work out?",
//     options: ["At home", "At the gym", "Outdoor"],
//     fieldName: "place",
//     type: "string",
//     components: "select",
//   },
//   {
//     idx: 25,
//     question: "Do you have any important event coming up?",
//     options: [
//       "Engagement/Wedding",
//       "Vacation",
//       "Sports event",
//       "Birthday",
//       "Reunion",
//       "Family gathering",
//       "Anniversary",
//       "Other important event",
//       "No event",
//     ],
//     fieldName: "event",
//     type: "string",
//     components: "select",
//   },
//   {
//     idx: 26,
//     question: "When is your event?",
//     options: ["3 weeks", "5 weeks", "7 weeks", "8 weeks", "I am not sure"],
//     fieldName: "event",
//     type: "string",
//     components: "select",
//   },
// ];

export const steps = [
  {
    idx: 1,
    question: "What's your gender?",
    options: ["Female", "Male", "Non-Binary", "Prefer not to say"],
    fieldName: "gender",
    type: "string",
    components: "select",
  },
  {
    idx: 2,
    question: "What's your goal",
    options: ["Gain muscle", "Lose weight", "Fitness"],
    fieldName: "goal",
    type: "string",
    components: "select",
  },
  {
    idx: 3,
    question: "Any previous workout experience?",
    options: [
      "Yes, I workout regularly",
      "Yes, less than a year ago",
      "Yes, more than 1 year ago",
      "No, I don't have any",
    ],
    fieldName: "priorExperience",
    type: "string",
    components: "select",
  },
  {
    idx: 4,
    question: "How old are you?",
    fieldName: "age",
    placeholder: 0,
    type: "number",
    components: "textbox",
  },
  {
    idx: 5,
    question: "How tall are you?",
    fieldName: "height",
    placeholder: 0,
    type: "number",
    units: ["cm", "ft"],
    components: "textbox",
  },
  {
    idx: 6,
    question: "What is your weight?",
    fieldName: "weight",
    placeholder: 0,
    type: "number",
    units: ["kg", "lbs"],
    components: "textbox",
  },
  {
    idx: 7,
    question: "Alright, Now what is your target weight?",
    fieldName: "targetWeight",
    placeholder: 0,
    type: "number",
    units: ["kg", "lbs"],
    components: "textbox",
  },
  {
    idx: 8,
    question: "Do you suffer from knee pain?",
    options: ["Yes", "No"],
    fieldName: "kneePainLevel",
    type: "string",
    components: "select",
  },
  {
    idx: 9,
    question: "How serious are your problem?",
    options: ["Mild pain", "Quite serious"],
    fieldName: "kneePainLevel",
    type: "string",
    components: "select",
  },
  {
    idx: 10,
    question: "How many do you walk daily?",
    options: ["more than 2 hours", "1-2 hours", "Less than 1 hour"],
    fieldName: "dailyWalkDistance",
    type: "string",
    components: "select",
  },
  {
    idx: 11,
    question: "What is your preferred mode of exercise?",
    options: [
      "Walking or Hiking",
      "Running or Jogging",
      "Cycling",
      "Strength Training",
      "Yoga or Stretching",
      "Group Fitness Classes",
      "Swimming",
      "Sports",
      "Home Workouts",
      "Not sure",
    ],
    fieldName: "preference",
    type: "string[]",
    components: "select",
  },
  {
    idx: 12,
    question: "What motivates you the most?",
    options: [
      "Feeling confident",
      "Being active",
      "Boosting immunity",
      "Improving sleep",
      "Feeling happier",
      "Boosting energy",
    ],
    fieldName: "motivation",
    type: "string[]",
    components: "select",
  },
];
